### ISSUE TITLE
Re-expose Plots.Shape

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/AgentsPlots.jl#12]
Flocking birds (and soon, probably) the bacteria example will use `Shape`, although we don't provide it.

**Comment by Datseris** [comment]
But `Shape` comes from Plots.jl...? Anyway, it isn't a big deal to re-export it.

**Comment by Libbum** [comment]
Yeah, I mean it's trivial to do 
```julia
using AgentsPlots
using Plots: Shape
```
if you need it, but just as a convenience we should re-export it since two of our examples use it.
