### ISSUE TITLE
Killed agents are still plotted in a graph 

### ISSUE THREAD

**Issue by xiaoweiz** [JuliaDynamics/AgentsPlots.jl#15]
Starting with a graph space, some nodes are killed later. Using `plotabm` still shows the initial graph structure. I'd like to only plot only the remaining nodes and edges, but can't figure out how to do it.

**Comment by Libbum** [comment]
When you kill an agent, you're not killing the space it resides in. The space you generate when creating your ABM is immutable in its structure (we don't provide `add_node!` or `delete_node!` for example). 

[LightGraphs](https://github.com/JuliaGraphs/LightGraphs.jl) is used under the hood, perhaps you wish to check out their docs to achieve what you need?

**Comment by Datseris** [comment]
@xiaoweiz On the plotting aspect the `graphplot` recipe from plots is used: https://docs.juliaplots.org/latest/graphrecipes/introduction/  perhaps there is a way to hide nodes.

Notice that you could make the nodes white as well if they have zero agents. This is easy from the `plotabm` interface.

What is in general impossible is to "destroy" a node. as Libbum said, the spatial structure is immutable, you can't destroy parts of it. You could create a new model with less nodes if you think this is necessary.

**Comment by Libbum** [comment]
Mutable spaces have been introduced in Agents.jl v4.0 (see `rem_node!` in the documentation for example), so the initial requirements of the question can now be fulfilled.
