### ISSUE TITLE
Package registration

### ISSUE THREAD

**Issue by kavir1698** [JuliaDynamics/AgentsPlots.jl#4]
Hi @Datseris 

This package now works without `GraphPlot`, `Compose`, `Cairo`, and `Fontconfig`. It only uses `Plots`. Can you please check if we are ready to register it? I am not confident with package registration yet.

**Comment by Datseris** [comment]
We can't because we need at least some basic tests in a `test` folder. Just test whether you can call the functions, etc. You can't see a plot on travis, but you can still plot without a backend.

**Comment by kavir1698** [comment]
We have tests now

**Comment by Datseris** [comment]
Can you update the README then to show test badges and have some information, e.g. linking the documentation via a badge? (copy/paste the readme of Agents.jl and change the link to the TravisCI)

**Comment by kavir1698** [comment]
Check the README please.

**Comment by Datseris** [comment]
Test are failing, see e.g. https://travis-ci.org/JuliaDynamics/AgentsPlots.jl/jobs/613189835

**Comment by kavir1698** [comment]
It should be because `Agents.jl`'s master is old.

**Comment by kavir1698** [comment]
Hi @Datseris 

Should `Test` be added to the package dependencies?

> ERROR: LoadError: ArgumentError: Package Test not found in current path:
> - Run `import Pkg; Pkg.add("Test")` to install the Test package.

**Comment by Datseris** [comment]
Yeap, you can do:

```
[compat]
julia = "1"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
```
to add `Test` so that it is only test dependncy

**Comment by kavir1698** [comment]
Tests fail on Windows. It looks like a Travis problem. What do you think?

**Comment by Datseris** [comment]
Seems like it. For now, I'd remove the windows tests. (Have you tested this on Windows by the way? locally?)

**Comment by kavir1698** [comment]
Yes, I mostly use Windows.

**Comment by kavir1698** [comment]
v0.1.0 is registered now.

**Comment by Datseris** [comment]
Cool, then we should update the docs of Agents to use it.

**Comment by kavir1698** [comment]
I thought the docs of Agents already mentions AgentsPlots.

**Comment by Datseris** [comment]
I am talking about actively `using AgentsPlots` and using them to actually show plots in as many pages of the documentation as possible.

`using AgentsPlots` in real runnable code was of course impossible before it was registered.

**Comment by Datseris** [comment]
(I don't want to announce Agents.jl before there are plots in the documentation. It is very important for a good first impression)

**Comment by kavir1698** [comment]
I see. Let's see where we can put a plot.
